[[redirects]]
  from = "/"
  to = "/"
  status = 200
  from = "/sign-in"
  to = "/sign-in"
  status = 200
  from = "/sign-up"
  to = "/sign-up"
  status = 200
  from = "/mrp-home"
  to = "/mrp-home"
  status = 200
  from = "/mrp"
  to = "/mrp"
  status = 200